import axios from 'axios';
import { GetStaticPaths, GetStaticProps } from 'next';
import Head from 'next/head';
import { ParsedUrlQuery } from 'querystring';

import styles from '@/styles/Home.module.scss';
import { Field, ReqUrlPreviewInfo } from '@/type/api';
import { Cache } from '@/utils/cache';

interface Params extends ParsedUrlQuery {
  id: string;
}

const cache = new Cache(4);

export const getStaticPaths: GetStaticPaths = () => {
  return {
    paths: [],
    fallback: 'blocking',
  };
};

// Get shortUrlInfo from db
const getShortUrlInfo = async (id: string) => {
  // Get targetUrl
  const axiosResp = await axios
    .get(`${process.env.NEXT_PUBLIC_HOST}/api/get/short-url-info/${id}`)
    .then((res) => res.data as Field);

  const shortUrlInfo = axiosResp.data as ReqUrlPreviewInfo;
  // Put the data into the cache.
  if (shortUrlInfo) cache.put(shortUrlInfo.id, shortUrlInfo);
  return shortUrlInfo;
};

// Updating visits from short url info
const updateVisits = (id: string, visits: number) => {
  axios.patch(
    `${process.env.NEXT_PUBLIC_HOST}/api/patch/short-url-info/${id}`,
    { visits }
  );
};

// Handle pre-rendering
export const getStaticProps: GetStaticProps<any> = async (context) => {
  const { id } = context.params as Params;

  const cacheValue = cache.get(id) as ReqUrlPreviewInfo;
  // If the target data is not in the cache, query the database.
  const shortUrlInfo = cacheValue || (await getShortUrlInfo(id));

  // Handle id not exist
  if (!shortUrlInfo) {
    return {
      notFound: true,
    };
  }

  const { title, description, imageUrl, targetUrl, visits } = shortUrlInfo;

  const newVisit = (visits ?? 0) + 1;
  shortUrlInfo.visits = newVisit;
  // Updating visits
  updateVisits(shortUrlInfo.id, newVisit);

  // Render pre-render page
  return {
    props: {
      title,
      description,
      imageUrl,
      targetUrl,
      visits: newVisit,
    },
    revalidate: 1,
  };
};

export default function Home({
  title,
  description,
  imageUrl,
  targetUrl,
  visits,
}: ReqUrlPreviewInfo) {
  // go to targetUrl
  const handleClick = () => {
    location.replace(targetUrl as string);
  };

  return (
    <>
      <Head>
        <title>{title}</title>
        {/* Set Open Graph Metadata */}
        <meta property="og:image" content={imageUrl} />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.card}>
        <span className={styles.url}>
          You are about to go to:<p>{targetUrl}</p>
        </span>

        <button className={styles.btn} onClick={handleClick}>
          &gt;
        </button>

        <span className={styles.visits}>visits: {visits}</span>
      </div>
    </>
  );
}
